const events = [
  {"Date":"08/28","Description":"First Day of School","Color":"Green"},
  {"Date":"09/01","Description":"Labor Day, No School","Color":"Red"},
  {"Date":"09/11","Description":"Open House","Color":"Green"},
  {"Date":"09/15","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"09/25","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"09/30","Description":"Picture Day","Color":"Green"},
  {"Date":"10/02","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"10/09","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"10/10","Description":"Inservice PK-12, No School","Color":"Red"},
  {"Date":"10/13","Description":"Indigenous People's Day, No School","Color":"Red"},
  {"Date":"10/16","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"10/20","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"10/23","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"10/24","Description":"Dance (Light up the night)","Color":"Green"},
  {"Date":"10/30","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"10/30","Description":"Unity Day","Color":"Green"},
  {"Date":"11/03","Description":"Early Release, PK-12 Conferences","Color":"Yellow"},
  {"Date":"11/04","Description":"Conferences, No School PK-12","Color":"Red"},
  {"Date":"11/11","Description":"Veteran's Day, No School","Color":"Red"},
  {"Date":"11/17","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"11/19","Description":"Picture Retakes","Color":"Green"},
  {"Date":"11/21","Description":"Movie Night @ 6:30pm","Color":"Green"},
  {"Date":"11/26","Description":"Holiday Break, No School","Color":"Red"},
  {"Date":"11/27","Description":"Holiday Break, No School","Color":"Red"},
  {"Date":"11/28","Description":"Holiday Break, No School","Color":"Red"},
  {"Date":"12/11","Description":"K-5 December Concert","Color":"Green"},
  {"Date":"12/15","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"12/22","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"12/23","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"12/24","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"12/25","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"12/26","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"12/29","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"12/30","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"12/31","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"01/01","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"01/02","Description":"Winter Break, No School","Color":"Red"},
  {"Date":"01/19","Description":"Inservice, PK-12","Color":"Red"},
  {"Date":"02/03","Description":"National School Counseling Week","Color":"Green"},
  {"Date":"02/04","Description":"National School Counseling Week","Color":"Green"},
  {"Date":"02/05","Description":"National School Counseling Week","Color":"Green"},
  {"Date":"02/06","Description":"Movie Night @ 6:30pm","Color":"Green"},
  {"Date":"02/09","Description":"Bring An Adult to Music Week","Color":"Green"},
  {"Date":"02/10","Description":"Bring An Adult to Music Week","Color":"Green"},
  {"Date":"02/11","Description":"Bring An Adult to Music Week","Color":"Green"},
  {"Date":"02/12","Description":"Bring An Adult to Music Week","Color":"Green"},
  {"Date":"02/13","Description":"Bring An Adult to Music Week","Color":"Green"},
  {"Date":"02/16","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"02/23","Description":"February Break, No School","Color":"Red"},
  {"Date":"02/24","Description":"February Break, No School","Color":"Red"},
  {"Date":"02/25","Description":"February Break, No School","Color":"Red"},
  {"Date":"02/26","Description":"February Break, No School","Color":"Red"},
  {"Date":"02/27","Description":"February Break, No School","Color":"Red"},
  {"Date":"03/02","Description":"February Break, No School","Color":"Red"},
  {"Date":"03/03","Description":"Inservice PK-12, No School","Color":"Red"},
  {"Date":"03/19","Description":"Early Release PK-12","Color":"Yellow"},
  {"Date":"03/20","Description":"Conferences, No School PK-12","Color":"Red"},
  {"Date":"03/21","Description":"Book Fair Kick-Off Event at Norwich","Color":"Green"},
  {"Date":"03/22","Description":"Book Fair","Color":"Green"},
  {"Date":"03/23","Description":"Book Fair","Color":"Green"},
  {"Date":"03/24","Description":"Book Fair","Color":"Green"},
  {"Date":"03/25","Description":"Book Fair","Color":"Green"},
  {"Date":"03/26","Description":"Book Fair","Color":"Green"},
  {"Date":"03/27","Description":"Book Fair","Color":"Green"},
  {"Date":"03/30","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"04/13","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"04/16","Description":"DBS School Musical @ 6:30pm","Color":"Green"},
  {"Date":"04/20","Description":"April Break, No School","Color":"Red"},
  {"Date":"04/21","Description":"April Break, No School","Color":"Red"},
  {"Date":"04/22","Description":"April Break, No School","Color":"Red"},
  {"Date":"04/23","Description":"April Break, No School","Color":"Red"},
  {"Date":"04/24","Description":"April Break, No School","Color":"Red"},
  {"Date":"05/07","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"05/13","Description":"K to 2 Spring Concert","Color":"Green"},
  {"Date":"05/14","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"05/21","Description":"3 to 5 Spring Concert","Color":"Green"},
  {"Date":"05/21","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"05/18","Description":"Late Start PK-8","Color":"Yellow"},
  {"Date":"05/25","Description":"Memorial Day, No School","Color":"Red"},
  {"Date":"05/28","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"06/04","Description":"Walk and Ride","Color":"Purple"},
  {"Date":"06/12","Description":"Ice Cream Social","Color":"Green"},
  {"Date":"06/15","Description":"Last Day","Color":"Green"},
  {"Date":"01/14","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"02/11","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"03/11","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"04/08","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"05/13","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"06/10","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"07/08","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"08/12","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"09/09","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"10/14","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"11/11","Description":"PTO Meeting @ 6pm","Color":"Blue"},
  {"Date":"12/09","Description":"PTO Meeting @ 6pm","Color":"Blue"}
];